version: "3.9"

services:
  django:
    image: django-botx:0.1
    build:
      context: .
    ports:
      - "8000:${DJANGO_PORT}"
    volumes:
      - ./Bot_X_API:/Bot_X_API
    command: sh -c "python3 manage.py runserver 127.0.0.1:8000"
  db:
    image: postgres:14.8-alpine3.18
    container_name: postgresdb
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB_NAME}
      - POSTGRES_USER=${POSTGRES_DB_USER}
      - POSTGRES_PASSWORD=${POSTGRES_DB_PASSWORD}
    ports:
      - "${POSTGRES_DB_PORT}:5432"
    volumes:
      - data:/var/lib/postgresql/data


  pg-admin:
    image: dpage/pgadmin4:7
    container_name: pgadmin
    depends_on:
      - db
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_LISTEN_PORT=${PGADMIN_LISTEN_PORT}
    ports:
      - "${PGADMIN_LISTEN_PORT}:5050"
    restart: always

volumes:
  data:
